export const items = {
    "Chrome_Heart":{
        name:"Chrome Heart",
        start:0,
        designed_by:"Klaws Design",
        description:"A hearty treat, this dress is perfect for the Metaverse retreat! The glistening hues and the bewitching iridescent is sure to grab eyeballs.",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Chrome+Heart/Media+for+Download/Chrome+Heart.zip"
            },
            glb_file:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Chrome+Heart/glb-universal+file/ChromeHeart3.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Chrome+Heart/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Chrome+Heart/Snap+AR/AR+Promo+Video_HR5.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/1.mp4"
    },
    "Flora_Flamboyance":{
        name:"Flora Flamboyance",
        start:40,
        designed_by:"Gulnara Gulia",
        description:"Antique and priceless, this outfit is sure to make your Metaverse Vogue seamless! The glistening hues and the sleeve just amps the look.",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Flora+Flamboyance/Media+for+Download/Flora+Flamboyance.zip"
            },
            glb_file:{
                status:false,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Flora+Flamboyance/Media+for+Download/Flora+Flamboyance.zip"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Flora+Flamboyance/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Flora+Flamboyance/Snap+AR/8.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/5.mp4"
    },
    "Puffy_Crossroads":{
        name:"Puffy Crossroads",
        start:10,
        designed_by:"SCSsubconscious",
        description:"We say blue and pink is the new gold as this dress is all set to make you the Metaverse Queen! Let you fashion ‘puff’ up.",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Puffy+Crossroads/Media+for+Download/Puffy+Crossroads.zip"
            },
            glb_file:{
                status:false,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Chrome+Heart/glb-universal+file/ChromeHeart3.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Puffy+Crossroads/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Puffy+Crossroads/Snap+AR/Sequence+01.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/2.mp4"
    },
    "Oyster_Spell":{
        name:"Oyster Spell",
        start:20,
        designed_by:"Yifan Pu",
        description:"As soft to the eyes as cotton, be the ‘cool’ Metaverse Diva with more so cool gloves and purse in hand’. Get ready to make a fashion statement like never before!",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Oyster+Spell/Media+for+Download/Oyster+Spell.zip"
            },
            glb_file:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Oyster+Spell/glb-universal+file/Oyster+Spell.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Oyster+Spell/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Oyster+Spell/Snap+AR/7_opt.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/3.mp4"
    },
    "Vibrance_Splash":{
        name:"Vibrance Splash",
        start:30,
        designed_by:"Technological Hippie",
        description:"Vibe with the vibrance Splash so perfectly well! Such enchanting colors, everybody’s gonna give a second glance!",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Vibrance+Splash/Media+for+Download/Vibrance+Splash.zip"
            },
            glb_file:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Vibrance+Splash/3d+Model+AR/Vibrance+Splash.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:true,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Vibrance+Splash/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Vibrance+Splash/Snap+AR/31.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/4.mp4"
    },
    "Rufflanza":{
        name:"Rufflanza",
        start:50,
        designed_by:"Xenia Joost",
        description:"To keep the Metaverse clean and pristine, the goddess with its extravagant dress has arrived. Guess what, it’s the dress that’s become the favorite talk of the town!",
        phase:1,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Rufflanza/Media+for+Download/Rufflanza.zip"
            },
            glb_file:{
                status:false,
                link:""
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:true,
            qr:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Rufflanza/Snap+AR/snapcode.png",
            video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+1/Rufflanza/Snap+AR/7.mp4"
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/6.mp4"
    },
    "Star_Cloak":{
        name:"Star Cloak",
        start:0,
        designed_by:"Klaws Design",
        description:"Be the galaxy’s dazzling ambassador with this outfit that radiates a rare shine and endearing hues. Take on the glitters!",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Star+Cloak/Media+for+Download/Star+Cloak.zip"
            },
            glb_file:{
                status:true,
                link:""
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/7.mp4"
    },
    "Celestial_Dream":{
        name:"Celestial Dream",
        start:10,
        designed_by:"Soledad Gallardo",
        description:"A cutting-edge design by Soledad Gallardo, that’s sure to illuminate your wardrobe collection. With bright hues and enchanting design, the outfit is sure to make a glorious hit in the Metaverse. Evoking a brilliant digi-craftsmanship, this is one of the super awesome outfits of our second NFT collection.",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Celestial+Dream/Media+for+Download/Celestial+Dream.zip"
            },
            glb_file:{
                status:false,
                link:""
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/8.mp4"
    },
    "Pop_Kiss":{
        name:"Pop Kiss",
        start:30,
        designed_by:"Yazata",
        description:"A bespoke world of imagination, channelised in reality, the outfit is a peppy, chic, and stupendous work of Yazata. Embodying pop culture in its most playful form, let your virtual wardrobe be ready to be kissed by the hottest outfit of Metaverse.",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Pop+Kiss/Media+for+Download/Pop+Kiss.zip"
            },
            glb_file:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Pop+Kiss/glb-universal+file/Pop+Kiss.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/10.mp4"
    },
    "Dazzling_Devil":{
        name:"Dazzling Devil",
        start:20,
        designed_by:"Lucii",
        description:"Straight from the streets of LA, the mind-blowing outfit by Lucii is ready to give your virtual closet a blend of futuristic and gala vibes. The multi-colored flashlights, the leather finesse, and the ‘ready-to-rock’ boots underline the designer’s cutting-edge creativity and imagination. Be the multi-hued spotlight in the Metaverse!",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Dazzling+Devil/Media+for+Download/Dazzling+Devil.zip"
            },
            glb_file:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Dazzling+Devil/glb-universal+file/Dazzling+Devil.glb"
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/9.mp4"
    },
    "Comic_Boom":{
        name:"Comic Boom",
        start:40,
        designed_by:"Fabeeo Breen",
        description:"An expert in curating virtual fashion, this outfit is a remarkable innovation of the designer Fabeeo. The pop landscape with all that jazz just got a splash of galvanizing hues with this multi-colored hoodie. Would you rather be the Lord of the Pop in the Metaverse and have all the limelight coming in you.",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Comic+Boom/Media+for+Download/Comic+Boom.zip"
            },
            glb_file:{
                status:false,
                link:""
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/11.mp4"
    },
    "Human_Masquerade":{
        name:"Human Masquerade",
        start:50,
        designed_by:"Givaa Damn",
        description:"Beyond the physical gravity is a world and it’s extremely magnificent’. A glimpse of the beautiful world of the universe and its creature, digi-crafted in enthralling outfits by Givaa. Investing a lot in the power of nature and imagination, the designer created the perfect outfit for Metascapes.",
        phase:2,
        get_3d_assets:{
            pfp:{
                status:true,
                link:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/Utilities/PHASE+2/Human+Masquerade/Media+for+Download/Human+Masquerade.zip"
            },
            glb_file:{
                status:false,
                link:""
            },
            metahuman:{
                status:false,
                link:""
            },
            cloneX:{
                status:false,
                link:"",
            }
        },
        metaverse_showcase:{
            oncyber:{
                status:true,
                link:""
            },
            spatial:{
                status:true,
                link:""
            },
            ar:{
                status:false,
            }
        },
        metaverse_wearables:{
            decenteraland:{
                status:true,
                link:""
            },
            sandbox:{
                status:false
            }
        },
        snapchat_ar:{
            status:false,
            qr:"",
            video:""
        },
        earn_passive:{
            status:false,
        },
        video:"https://xrcouture-xrcie.s3.ap-south-1.amazonaws.com/Metadrip/12.mp4"
    },
}
